import {escapeHtml as e, money, housePath} from './offers.mjs'
export function offerMarkup(data,id,assets={}) {
 const h=data.houses.find(h=>h.id===id); if(!h) throw new Error('Nieznany dom')
 const img=p=>assets[p]?`${p}?v=${assets[p]}`:p
 const ask=h.status==='Sprzedany' ? '/#kontakt' : `/?dom=${id}#kontakt`
 const statusClass={'Dostępny':'available','Rezerwacja':'reserved','Sprzedany':'sold'}[h.status]
 const note=h.status==='Sprzedany'?'Ten dom jest sprzedany. Sprawdź pozostałe domy.':h.status==='Rezerwacja'?'Ten dom jest zarezerwowany. Zapytaj o aktualną dostępność.':'Zapytaj o dom lub umów prezentację działki.'
 return `<header class="offer-header"><a href="/" aria-label="Domy na Polnej — strona główna"><strong>Domy na Polnej</strong><span>GRABIK · KOŁO ŻAR</span></a><a href="/#domy">Wszystkie domy <span aria-hidden="true">↗</span></a></header>
 <main id="main" class="offer-shell"><nav class="offer-breadcrumb" aria-label="Okruszki"><a href="/">Domy na Polnej</a><span aria-hidden="true"> / </span><span aria-current="page">${e(h.name)}</span></nav>
 <section class="offer-hero"><div class="offer-visual"><img src="${e(h.image)}" width="1672" height="941" alt="${e(h.name)} — wizualizacja elewacji" fetchpriority="high"><small>Wizualizacja · wspólny projekt domów A–E</small></div><div class="offer-summary"><p class="offer-kicker">DZIAŁKA ${e(h.parcel)}</p><h1>${e(h.name)} w Grabiku</h1><span class="offer-status offer-status--${statusClass}">${e(h.status)}</span><p>Wolnostojący dom ${e(h.area)} m² z własną działką ${e(h.plot)} m².</p><dl class="offer-facts">${[['Powierzchnia domu',h.area+' m²'],['Działka',h.plot+' m²'],['Pokoje',h.rooms],['Miejsca postojowe',h.parking]].map(([a,b])=>`<div><dt>${e(a)}</dt><dd>${e(b)}</dd></div>`).join('')}</dl><p class="offer-price"><small>Cena oferty brutto</small><strong>${e(money(h.price))}</strong></p><p>${e(note)}</p><a class="offer-button" href="${ask}" data-event="house_contact_click" data-house="${id}">${h.status==='Sprzedany'?'Zapytaj o inne domy':'Zapytaj o dom '+e(h.id)} →</a>${h.pdf?`<a class="offer-pdf" href="${e(h.pdf)}" target="_blank" rel="noopener" data-event="house_pdf_download" data-house="${id}">Pobierz kartę domu ${e(h.id)} (PDF) ↓</a>`:''}</div></section>
 <section class="offer-layout"><div><p class="offer-kicker">JEDEN POZIOM · PRZEMYŚLANY UKŁAD</p><h2>Dom, który działa na co dzień</h2><p>Salon z jadalnią, kuchnia ze spiżarnią, sypialnia rodziców, dwa pokoje, gabinet, dwie łazienki i pomieszczenie gospodarcze.</p><p>Pompa ciepła, ogrzewanie podłogowe, rekuperacja i rolety elektryczne — szczegółowy zakres opisuje standard wykończenia.</p><a href="/?dom=${id}#uklad">Zobacz interaktywny rzut →</a>${data.standardPdf?`<a class="offer-pdf" href="${e(data.standardPdf)}" target="_blank" rel="noopener">Standard wykończenia (PDF) ↓</a>`:''}</div><img src="${e(img('/assets/images/layout/plan-2d-precise.webp'))}" width="1195" height="896" alt="Rzut parteru — wspólny układ domów A–E" loading="lazy"></section>
 <section class="offer-interior"><h2>Przestrzeń do urządzenia po swojemu</h2><div>${[['int18-salon-wysoki-sufit','Salon i jadalnia'],['int05-kuchnia-barek','Kuchnia']].map(([slug,title])=>`<figure><img src="${e(img('/assets/images/spacer-360/interior/webp/'+slug+'.webp'))}" width="1672" height="941" alt="${e(title)} — przykładowa aranżacja" loading="lazy"><figcaption>${e(title)} · przykładowa aranżacja</figcaption></figure>`).join('')}</div><a class="offer-button" href="/?dom=${id}#spacer-360">Otwórz wirtualny spacer →</a><p>Wizualizacje przedstawiają przykładową aranżację. Wiążący zakres domu i wykończenia wynika z dokumentacji oraz umowy.</p></section>
 <section class="offer-other"><h2>Pozostałe domy na Polnej</h2><div>${data.houses.filter(x=>x.id!==id).map(x=>`<a href="${housePath(x.id)}"><strong>${e(x.name)}</strong><span>${e(x.plot)} m² działki · ${e(x.status)}</span><b>${e(money(x.price))}</b></a>`).join('')}</div></section></main>
 <footer class="offer-footer"><strong>Domy na Polnej · Grabik koło Żar</strong><a href="${e(data.contact.phoneHref)}" data-event="phone_click" data-house="${id}">${e(data.contact.phoneDisplay)}</a><a href="${e(data.contact.emailHref)}" data-event="email_click" data-house="${id}">${e(data.contact.email)}</a><a href="/polityka-prywatnosci/">Prywatność</a><a href="/polityka-cookies/">Cookies</a><button type="button" id="offer-cookie-settings">Ustawienia prywatności</button></footer>`
}
