import {chromium,expect} from '@playwright/test'
import {startServer} from './browser-utils.mjs'
import {mkdirSync,writeFileSync} from 'node:fs'
const server=await startServer('preview-server.mjs',4186)
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined})
const results=[];const output='docs/audit-rc3';mkdirSync(output,{recursive:true})
try{
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'})
 await page.goto(server.url);await page.getByRole('button',{name:'Tylko niezbędne',exact:true}).click()
 await page.locator('#contact-name').fill('Przykładowe imię')
 await page.locator('.plot-label').filter({hasText:'C'}).click()
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.copied=value}}})})
 await page.getByRole('button',{name:'Kopiuj link do domu C',exact:true}).click()
 await expect(page.locator('.house-card__share-status')).toBeVisible()
 expect(await page.evaluate(()=>window.copied)).toBe(server.url+'/?dom=C#domy')
 await expect(page.locator('#contact-name')).toHaveValue('Przykładowe imię')
 results.push('Copy link preserves unfinished enquiry and selected house')
 await page.locator('.plot-label').filter({hasText:'E'}).click()
 await expect(page.locator('.house-card__share-status')).toHaveCount(0)
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}})})
 await page.getByRole('button',{name:'Kopiuj link do domu E',exact:true}).click()
 await expect(page.locator('.house-card__share-fallback input')).toHaveValue(server.url+'/?dom=E#domy')
 await expect(page.locator('.house-card__share-fallback input')).toBeFocused()
 results.push('Denied clipboard shows selected, focusable URL; changed house resets feedback')
 await page.goto(server.url+'/?dom=D#domy');await expect(page.locator('.plot-label[aria-pressed=true]')).toContainText('D')
 results.push('Shared URL opens the correct house')
 await page.setViewportSize({width:844,height:390});await page.goto(server.url)
 await page.getByRole('button',{name:'Otwórz menu',exact:true}).click()
 await page.locator('.mobile-nav__contact').click()
 await expect(page.locator('#contact-title')).toBeFocused()
 await expect(page.getByRole('button',{name:'Otwórz menu',exact:true})).toHaveAttribute('aria-expanded','false')
 await expect(page.locator('#kontakt')).not.toHaveAttribute('inert','')
 results.push('Short landscape viewport: menu scrolls to contact, closes and restores focus destination')
 await page.setViewportSize({width:390,height:844})
 await page.goto(server.url+'/#lista-domow')
 expect(await page.locator('#lista-domow').evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(100)
 await page.locator('.homes-mobile-list').getByRole('button').last().click()
 await page.locator('.house-sheet').getByRole('button',{name:'Kopiuj link do domu E'}).click()
 await page.screenshot({path:output+'/mobile-house.png'})
 await page.keyboard.press('Escape');await expect(page.locator('.house-sheet')).toHaveCount(0)
 results.push('Mobile comparison anchor and share in house dialog remain usable')
 await page.close()
}finally{writeFileSync(output+'/regression.json',JSON.stringify(results,null,2));await browser.close();server.child.kill()}
console.log(results)
