import { existsSync, readFileSync } from 'node:fs'
const read=(path)=>readFileSync(path,'utf8')
const assert=(value,message)=>{if(!value)throw new Error(message)}
for(const path of ['public/assets/images/dnp-masterplan.svg','public/assets/images/ui/masterplan-compass.png','api/contact.php','api/analytics.php','public/robots.txt','public/sitemap.xml','scripts/prepare-dist.mjs']) assert(existsSync(path),`Brak ${path}`)
assert(!existsSync('api/config.php'),'api/config.php nie może trafić do repo')
assert(!existsSync('public/assets/images/masterplan.webp'),'Niepotrzebny masterplan.webp nadal istnieje')
const masterplan=read('src/components/house-selector/Masterplan.tsx')
assert(masterplan.includes('dnp-masterplan.svg'),'Masterplan nie używa oryginalnego SVG')
assert(masterplan.includes('masterplan-compass.png'),'Masterplan nie używa oryginalnego kompasu')
assert(!masterplan.includes('masterplan.webp'),'Kod masterplanu nadal odwołuje się do WebP')
const html=read('index.html');for(const token of ['rel="canonical"','property="og:url"','name="twitter:card"','application/ld+json'])assert(html.includes(token),`SEO: brak ${token}`)
const main=read('src/main.tsx');for(const token of ['PrivacyPolicy','CookiePolicy','NotFound','isLocalHost'])assert(main.includes(token),`Routing: brak ${token}`)
assert(read('public/.htaccess').includes('R=404'),'Brak prawdziwego 404 w .htaccess')
const faq=read('src/data/faq.ts');assert((faq.match(/\n    id:/g)??[]).length===17,'FAQ powinno mieć 17 pytań')
const faqView=read('src/sections/FaqContact/FaqContact.tsx');for(const token of ['Inwestycja i dom','Zakup i formalności','Cena i bezpieczeństwo','aria-expanded','aria-controls','emailPattern','/polityka-prywatnosci/'])assert(faqView.includes(token),`FAQ/formularz: brak ${token}`)
assert(!faqView.includes('faq-section__image'),'FAQ nadal zawiera usunięte zdjęcie')
const schedule=read('src/data/schedule.ts');assert((schedule.match(/state: 'completed'/g)??[]).length===0,'Harmonogram: 0 zakończonych');assert((schedule.match(/state: 'current'/g)??[]).length===1,'Harmonogram: 1 aktualny');assert((schedule.match(/state: 'planned'/g)??[]).length===4,'Harmonogram: 4 planowane')
const hero=read('src/sections/Hero/Hero.tsx');assert(hero.includes('od 779 000 zł'),'Hero nie pokazuje ceny wejściowej');assert(hero.includes('prefers-reduced-motion'),'Hero nie respektuje reduced motion')
assert(!read('src/sections/Journal/Journal.tsx').includes('journal-newsletter'),'Newsletter demo nadal istnieje')
const analytics=read('src/lib/analytics.ts');for(const token of ['sessionId','sendBeacon','ANALYTICS_CONSENT_KEY'])assert(analytics.includes(token),`Analityka: brak ${token}`)
const styles=read('src/styles/v6-production.css');assert(styles.includes('min-width:880px')&&styles.includes('max-width:1100px'),'Brak poprawki FAQ 1024 px');assert(styles.includes('.legal-page')&&styles.includes('.not-found'),'Brak styli legal/404')
console.log('PASS source-check V6.1: SVG masterplanu, routing/404, API, SEO, 17 FAQ, 0/1/4, formularz, analityka i responsywność')
